### PR TITLE
Add support for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by ckaenzig**

### CODE REVIEW

**Comment by dabelenda** [comment]
You can also add the OS in the supported array in metadata.json so that tests are actually run on it, too.

**Comment by ckaenzig** [comment]
@dabelenda good point, I added that.

**Comment by dabelenda** [comment]
ah... sorry you also need to change the .travis.yml to add the tests on ubuntu 16.04:

diff --git a/.travis.yml b/.travis.yml
index 0a460d2..2feee5f 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -60,6 +60,13 @@ matrix:
     sudo: required
     dist: trusty
     services: docker
-    env: BEAKER_set="ubuntu-16.04"
-    bundler_args:
-    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb
-  - rvm: default
-    sudo: required
-    dist: trusty
-    services: docker
   env: BEAKER_set="centos-5"
   bundler_args:
   script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/*_spec.rb

**Comment by dabelenda** [comment]
Ok, this seems to be a bug in the adiscon package... if rsyslog is installed using the native ubuntu xenial package it works. So let us use this package instead:

diff --git a/manifests/params.pp b/manifests/params.pp
index 3db6154..81db986 100644
--- a/manifests/params.pp
+++ b/manifests/params.pp
@@ -176,6 +176,21 @@ class rsyslogv8::params {
               $_version_os_family_umask                = undef
               $_version_os_family_pin_packages         = undef
             }
-            '16.04' : {
-              $_version_os_family_manage_repo          = false
-              $_version_os_family_repo_data            = {}
-              $_version_os_family_relp_package_name    = undef
-              $_version_os_family_rsyslog_package_name = undef
-              $_version_os_family_gnutls_package_name  = false
-              $_version_os_family_run_user             = undef
-              $_version_os_family_run_group            = undef
-              $_version_os_family_spool_dir            = undef
-              $_version_os_family_modules              = undef
-              $_version_os_family_perm_file            = undef
-              $_version_os_family_perm_dir             = undef
-              $_version_os_family_umask                = undef
-              $_version_os_family_pin_packages         = undef
-            }
           default: {
             fail("Unsupported operatingsystemmajrelease (${::operatingsystem}) ${::operatingsystemmajrelease}")
           }

**Pull request merged**
